export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const SET_EXERCISE = 'SET_EXERCISE';
export const SET_EXERCISES = 'SET_EXERCISES';
export const SET_EDIT_MODE = 'SET_EDIT_MODE';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';